import {
    OrbitControls, useGLTF, useTexture
} from "@react-three/drei";
import { Canvas, useThree } from "@react-three/fiber";
import React, { Suspense, useRef } from "react";
import useRefs from "react-use-refs";

interface LaptopProps {
    projectImage: string;
}

const Laptop: React.FC <LaptopProps> = ({ projectImage, ...props }) => {
  const { width, height } = useThree((state) => state.viewport);
  const [group, mbp16, keyLight, stripLight, fillLight, left, right] =
    useRefs();
  const moraisMovelaria = useTexture(projectImage);
  return (
    <>
      <spotLight position={[0, -width * 0.7, 0]} intensity={0.5} />
      <directionalLight ref={keyLight} castShadow intensity={6}>
        <orthographicCamera
          attachObject={["shadow", "camera"]}
          args={[-10, 10, 10, -10, 0.5, 30]}
        />
      </directionalLight>
      <group ref={group} position={[0, -height / 2.65, 0]} {...props}>
        <spotLight
          ref={stripLight}
          position={[width * 2.5, 0, width]}
          angle={0.19}
          penumbra={1}
          intensity={0.25}
        />
        <spotLight
          ref={fillLight}
          position={[0, -width / 2.4, -width * 2.2]}
          angle={0.2}
          penumbra={1}
          intensity={2}
          distance={width * 3}
        />
        <Laptop3D ref={mbp16} texture={moraisMovelaria} scale={width / 45} />
        <OrbitControls
          enableRotate={true}
          enablePan={false}
          enableZoom={false}
          minPolarAngle={Math.PI / 2 + 0.06}
          maxPolarAngle={Math.PI / 2}
          autoRotate={true}
        />
      </group>
    </>
  );
};

/*
  Auto-generated by: https://github.com/pmndrs/gltfjsx
  */

const Laptop3D: React.FC = ({ ...props }) => {
  const group = useRef();
  const { nodes, materials } = useGLTF("/mbp-v1-pipe.glb");
  return (
    <group ref={group} {...props} dispose={null} position={[0, 1, 0]}>
      <group position={[0, -0.41, -11.35]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.back_1.geometry}
          material={nodes.back_1.material}
        />
        <mesh
          geometry={nodes.back_2.geometry}
          material={nodes.back_2.material}
        />
        <mesh geometry={nodes.matte.geometry} material={materials.matte} />
      </group>
      <mesh geometry={nodes.body_1.geometry} material={nodes.body_1.material} />
      <mesh geometry={nodes.body_2.geometry} material={nodes.body_2.material} />
    </group>
  );
};

useGLTF.preload("/mbp-v1-pipe.glb");

export default Laptop;